import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import { withApollo } from '../lib/withApollo'
import { useFetchUser } from '../lib/user'

function Home() {
  const { user, loading } = useFetchUser()
  if (loading) {
    return <div>Loading...</div>
  }

  if (!loading && !user) {
    return (
      <>
        <div>
          <Head>
            <title>Wasify</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>

        <Layout />
      </>
    );  
  } else {
    
  }
  
}

export default withApollo()(Home)